### ISSUE TITLE
Just change two item. How can i do?

### ISSUE THREAD

**Issue by noty1311** [andyken/DraggableGridView#1]
When i change item1 with item3, and not move item2. how do it, please?

当我拖曳项目1，想与项目3对调时，能否不移动中间的项目2. 请问该如何修正呢?

**Comment by andyken** [comment]
在onTouch的action_move方法中 去掉animateGap的调用 并修改重新排列子元素的方法reorderChildren只调换原位置和目标位置的两个元素
